### PR TITLE
Implement mprotect

### PR DESCRIPTION
**Pull request by bkjg**
Implement mprotect. The most significant addition here is splitting the segments when we are trying to change the permissions only of the part of them.

### CODE REVIEW

**Comment by cahirwpz** [comment]
Please resolve conflicts.

**Comment by cahirwpz** [comment]
@franciscozdo Please evaluate this PR for useful changes in the context of adapting Cranor's `amap`.

**Comment by franciscozdo** [comment]
The only things we could take from this PR are changes made to pmap.

**Comment by cahirwpz** [comment]
I reckon this PR should be split into two parts. The first would be focused on adding support for splitting `vm_map_entry`-ies. The second should change `vm_map_entry` access permissions.

**Comment by cahirwpz** [comment]
Superseded by #1370

**Pull request closed without merging**
