### PR TITLE
PCI isn't a PCI attached device.

### PR DESCRIPTION
**Pull request by MichalBlk**
Remove the `DEV_PCI_BUS` marker form the PCI bus device.

### CODE REVIEW

**Review by mohrcore — APPROVED** [review]
LGTM.

**Review by ThomasStachovsky — COMMENTED** [review]
That's odd. 

CircleCI says it failed compiled with gcc for mips with seed 835631730 on the sleepq_timed (at /root/mimiker/sys/tests/sleepq_timed.c:83) test which as far as I see doesn't really have anything to do with the changes in this pull request. 

When I ran a test on this build with the same seed, it **did not** fail.

**Review by mohrcore — APPROVED** [review]
Obviously approved.

**Review by komik0 — APPROVED** [review]
LGTM

**Comment by cahirwpz** [comment]
@MichalBlk I'm somewhat confused – can you explain why this change is needed?

**Comment by MichalBlk** [comment]
In the definition of `device_t` we can see
```C
device_bus_t bus; /* (for children) type of bus we're attached to */
```
But in our scenario, PCI bus is not attached to a PCI bus.

**Review by cahirwpz — APPROVED** [review]
LGTM

**Pull request merged**
