### PR TITLE
Adding kgprof instrumentation for AArch64

### PR DESCRIPTION
**Pull request by wiklam**
Depends on #1062

### CODE REVIEW

**Comment by pj1031999** [comment]
@wiklam mark me for review when #1062 will be merged.

**Comment by cahirwpz** [comment]
Please resolve conflicts.

**Comment by pj1031999** [comment]
@wiklam bump

**Comment by MichalBlk** [comment]
I updated this PR. @wiklam please verify the update.

**Review by MichalBlk — APPROVED** [review]

**Review by cahirwpz — APPROVED** [review]

**Pull request merged**
