### PR TITLE
[RISCV] Context switch.

### PR DESCRIPTION
**Pull request by MichalBlk**
Context switch implementation.

### CODE REVIEW

**Review by pj1031999 — APPROVED** [review]
LGTM

**Comment by pj1031999** [comment]
@cahirwpz @MichalBlk you should add risc-v build to CI to prevent future build regressions.

**Review by cahirwpz — APPROVED** [review]
Please remove unnecessary references to `FPU`.

**Comment by MichalBlk** [comment]
The unnecessary FPU conditional compilation is gone.

**Pull request merged**
