### PR TITLE
initial gdb scripts for thread debugging

### PR DESCRIPTION
**Pull request by psie**

### CODE REVIEW

**Comment by rafalcieslak** [comment]
We've recently implemented a list of all threads and thread IDs, see (5deb0ed807). You may want to incorporate these features in your scripts.

**Comment by coodie** [comment]
@psie 
Would you like me to do it or you want to do it?

**Comment by psie** [comment]
@rafalcieslak Thanks, that will come in very handyi ndeed.
@coodie I'd rather you do it since you need this quick and I am progressing slowly.

**Comment by coodie** [comment]
@psie 
Okay, I'm fine with it :).

**Comment by coodie** [comment]
@cahirwpz 
Is this a problem to merge this now? I don't feel like playing with git for couple of hours and move files between branches because there can be more commands... while these are ok. I'd rather this to be merged and ready for use by everyone and then make new branch and PR from master.

**Comment by cahirwpz** [comment]
I'm somewhat confused. Should I close #108?

**Pull request merged**
