### PR TITLE
Add read/write operations for tmpfs

### PR DESCRIPTION
**Pull request by xThaid**
Read and write operations for tmpfs are now fully working. Addressing a file's data blocks is based on a structure adopted from [ext2](http://web.mit.edu/tytso/www/linux/ext2intro.html) filesystem. The key features are fixed logical block size, ease of data location and indirect blocks. Default level of indirection is 2, which should be enough (file's size can be up to roughly 4GiB). 
I also have written some unit tests for this code.

### CODE REVIEW

**Comment by cahirwpz** [comment]
I wonder... maybe you tried to make the code too generic by assuming someone will be tempted to change value of `INDIR_LEVELS`?

**Comment by xThaid** [comment]
I know this code may be too generic, but I feel like this is more clear and compact than hard-coding two levels of indirection. In my opinion, changing file size one block at a time also simplifies whole logic. I tried to write something else, but all resulted in rather longer and repetitive code with multiple if statements.

**Comment by cahirwpz** [comment]
I'm willing to accept simpler code, even if it involves making it more verbose.

**Comment by xThaid** [comment]
Second version is in another PR #624.

**Pull request closed without merging**
