### PR TITLE
RTL8139: Improve qemu config

### PR DESCRIPTION
**Pull request by komik0**
Now with:
- ```ssh -p10022 root@localhost```- we are able to gen some traffic.
- ```/usr/sbin/tcpdump -qxxxns 0 -A -r rtl8139.pcap``` - we are able to inspect traffic

### CODE REVIEW

**Comment by cahirwpz** [comment]
@komik0 We don't even look into PRs that do not pass all checks in CircleCI.

**Comment by komik0** [comment]
@cahirwpz - done, ready for review

**Review by pj1031999 — COMMENTED** [review]
It looks good enough for our needs.
You put network config in machine independent layer of configuration - could you confirm that the **same** device works on _AArch64_?

**Comment by komik0** [comment]
@pj1031999 thanks for pointing this issue. rtl8139 is not supported on qemu arch64. So I've moved that code under malta-dependent options

**Review by pj1031999 — APPROVED** [review]
LGTM

**Review by MichalBlk — APPROVED** [review]
LGTM

**Comment by cahirwpz** [comment]
Please resolve conflicts.

**Comment by komik0** [comment]
Moved to #988

**Comment by cahirwpz** [comment]
Merge with `master` as #988

**Pull request closed without merging**
