### PR TITLE
Pass arguments to user-space programs via kernel command line.

### PR DESCRIPTION
**Pull request by pwit81**
Pass arguments/environment to user-space programs. For now only user argv handling is implemented. 

Example usage:
`$ ./launch init_args=\"sandbox dummy foo\" init=/bin/sandbox`

### CODE REVIEW

**Comment by cahirwpz** [comment]
Why not simplify kernel launch command to:
```
$ ./launch init=\"/bin/sandbox dummy foo\"
```

**Comment by cahirwpz** [comment]
@bgrm Please finish this task and clean up the code.

**Comment by bgrm** [comment]
@cahirwpz I've noticed some issues with running launcher with kernel arguments containing strings of specific format, like " -str", " =str", or a character " | ". For example:

1. following command:
`$ ./launch -t klog-quiet=1 init=\"/bin/sandbox -dummy\" `
results with:
```
usage: launch [-h] [-k KERNEL] [-D DEBUGGER] [-d] [-t] [-g] [ARGS [ARGS ...]]
launch: error: argument -d/--debug: ignored explicit argument 'ummy"'
```

2. command:
`$ ./launch -t klog-quiet=1 init=\"/bin/sandbox =dummy\"`
results with:
`zsh: dummy" not found`

3. command:
`$ ./launch -t klog-quiet=1 init=\"/bin/sandbox |dummy\"`
results with:
```
zsh: command not found: dummy"
(...)
2019/01/27 18:21:31 socat[26877] E write(1, 0x556c2031b1d0, 1): Broken pipe
qemu-mimiker-mipsel: terminating on signal 15 from pid 26872 (python3)
```

It seems that there's a bug in the launcher's parser. But actually I don't know if it's the case in the master branch.

**Comment by cahirwpz** [comment]
Far too many changes has been merged into source tree to recover this PR to working state. It has to be rewritten from scratch most likely. Hence I close it.

**Pull request closed without merging**
