### PR TITLE
Unit tests and another fix to ring buffer impl.

### PR DESCRIPTION
**Pull request by pwit81**
Corrected a bug and added some unit tests.

### CODE REVIEW

**Comment by cahirwpz** [comment]
For the record: I backported `ringbuf` fix into `master`. Thanks for finding it!

**Comment by jpszczolowski** [comment]
Why don't we have `ringbuf` tests in master branch?

**Comment by jpszczolowski** [comment]
@pwit81 do we need `kmalloc` and `UIO_SINGLE_KERNEL` in these tests? I think that `ringbuf` tests should use `ringbuf` and as few other modules as possible. If we need a buffer, we can use a local array inside test function.

**Comment by cahirwpz** [comment]
@pwit81 I'm somewhat confused why this PR introduces `ringbuf_alloc` and `ringbuf_destroy`.

**Comment by jpszczolowski** [comment]
@pwit81 ok, I'm sorry, use of `UIO_SINGLE_KERNEL` in the tests is necessary. But I'm not sure whether we want to introduce `ringbuf_alloc`, `ringbuf_destroy` and `kmem_pool` inside `ringbuf` implementation and tests.
I've:
- changed implementation of produce and consume and added asserts (so that now these functions cannot be used wrong),
- moved each test into separate KTEST_ADD.

**Comment by jpszczolowski** [comment]
@cahirwpz yes, exactly.

**Comment by cahirwpz** [comment]
I think we can safely replace `ringbuf_alloc`, `ringbuf_destroy` with
```c
void ringbuf_init(ringbuf_t *rb, void *buf, size_t buflen) { ... }
```

**Comment by jpszczolowski** [comment]
@cahirwpz in my opinion this PR is ready

**Pull request merged**
