### PR TITLE
PTE size extension to 8B (draft) 

### PR DESCRIPTION
**Pull request by strzkrzysiek**
PTE size extended to 8B in order to be able to store additional flags. #159

### CODE REVIEW

**Comment by cahirwpz** [comment]
We discussed the changes during last meeting. Has been there any progress since then?

**Comment by strzkrzysiek** [comment]
Yes. Some should be pushed by the evening.

**Comment by cahirwpz** [comment]
I'm afraid there're still some bugs in modified `pmap.c`. Please make sure to run all relevant tests, e.g.:

```
./launch -t test=vm_map
```

**Comment by strzkrzysiek** [comment]
I have investigated a little bit the cause of the failing vm_map test.

The first problem was while setting PTE. It caused exception because sometimes respective PDE entry was no longer present in TLB. It is fixed in the next commit. 

The second problem is the simplified TLB Refill procedure. Why? The very first store operation is done on address `0x01001000`. Obviously, TLB Refill exception is raised and the control is passed to the handler. There we stopped distinguish between even and odd pages so the even-page PTE is loaded first. This PTE is stored at the address `0xC0008000`. This operation again raises an exception which this time passes the control to the General Exception Handler and in consequence to the TLB Exception Handler. This handler has no single clue which page is actually requested because the only thing it has is BadVAddr register which contains `0xC0008000`. This is translated back into the address `0x0100000` and the Page Fault procedure is called. It obviously fails, because this page is mapped but has no access rights.

What I recommend for now is to keep the TLB Refill Handler in the extended version for now. I have had a brief look into the source code of FreeBSD and they don't do the trick but I haven't figured it out yet how do they do it. Here is the [link](bxr.su/FreeBSD/sys/mips/mips/exception.S#131).

Accepting this pull request will let me proceed with further work. About the possible solutions it would be nice to talk in person.

**Comment by strzkrzysiek** [comment]
I have no idea why the check fails. Trying to reproduce this failure (seed: 2181325586) results in a success using my machine. Any ideas what can be the cause of this inconsistency?

**Comment by cahirwpz** [comment]
It's not difficult to crash `referenced_modified_test`. You can do it easily by running `run_tests.py`.

For instance, following test run `launch -t test=all seed=930810437 repeat=5` fails with log:

```Running test ref_mod.
[pmem] pm_alloc {paddr:348000 size:2}
[pmap.c:101] Page directory table allocated at c0802000
[pmem] pm_alloc {paddr:3f0000 size:16}
[pmem] pm_alloc {paddr:34e000 size:2}
[pmap.c:166] Page table fragment c0006000 allocated at 0034e000
[pmap.c:244] Add mapping for page 00ff8000 (PTE at c0007fc0)
[pmap.c:244] Add mapping for page 00ff9000 (PTE at c0007fc8)
[pmap.c:244] Add mapping for page 00ffa000 (PTE at c0007fd0)
[pmap.c:244] Add mapping for page 00ffb000 (PTE at c0007fd8)
[pmap.c:244] Add mapping for page 00ffc000 (PTE at c0007fe0)
[pmap.c:244] Add mapping for page 00ffd000 (PTE at c0007fe8)
[pmap.c:244] Add mapping for page 00ffe000 (PTE at c0007ff0)
[pmap.c:244] Add mapping for page 00fff000 (PTE at c0007ff8)
[pmem] pm_alloc {paddr:34c000 size:2}
[pmap.c:166] Page table fragment c0008000 allocated at 0034c000
[pmap.c:244] Add mapping for page 01000000 (PTE at c0008000)
[pmap.c:244] Add mapping for page 01001000 (PTE at c0008008)
[pmap.c:244] Add mapping for page 01002000 (PTE at c0008010)
[pmap.c:244] Add mapping for page 01003000 (PTE at c0008018)
[pmap.c:244] Add mapping for page 01004000 (PTE at c0008020)
[pmap.c:244] Add mapping for page 01005000 (PTE at c0008028)
[pmap.c:244] Add mapping for page 01006000 (PTE at c0008030)
[pmap.c:244] Add mapping for page 01007000 (PTE at c0008038)
[referenced_modified_test.c:68] Storing at address: 0x0xff8000
[referenced_modified_test.c:68] Storing at address: 0x0x1006000
[referenced_modified_test.c:68] Storing at address: 0x0xffd000
[referenced_modified_test.c:68] Storing at address: 0x0x1004000
[referenced_modified_test.c:63] Loading 0 from address: 0x0xffb000
[referenced_modified_test.c:68] Storing at address: 0x0x1007000
[referenced_modified_test.c:63] Loading 0 from address: 0x0x1005000
[referenced_modified_test.c:63] Loading 0 from address: 0x0xffc000
[referenced_modified_test.c:68] Storing at address: 0x0x1003000
[referenced_modified_test.c:63] Loading 0 from address: 0x0x1001000
[pmap.c:553] Assertion '0xc0000000 > orig_vaddr || orig_vaddr >= 0xc0000000 + ((1024 * 1024) * sizeof(pte_t))' failed!
[thread.c:91] Thread 'main' {0x8033e208} has finished.
```

**Comment by cahirwpz** [comment]
After all, we're going to keep _referenced_ and _modified_ bits in `vm_page` structures. The development of `pmap.c` went in completely different directions and we're not going to make any use of this code, unfortunately.

**Pull request closed without merging**
